export * from './test.controller';
export * from './auth.controller';
export * from './minio.controller';
export * from './parser.controller';
export * from './person.controller';
export * from './picture.controller';
export * from './publicPreview.controller';
export * from './user.controller';
export * from './webtorrent.controller';
