version: "3.7"

services:
  backend:
    command: npm run start:dev
    volumes:
      - ./backend/logs:/app/backend/logs
      - ./backend:/app/backend
      - /app/backend/node_modules

volumes:
  logs: