version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
    ports:
      - ${RMQ_PORT}:${RMQ_PORT}
      - ${RMQ_PORT_PLUS}:${RMQ_PORT_PLUS}

  s3:
    image: minio/minio:latest
    container_name: minio
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - "9001:9001"
    volumes:
      - ./storage-minio:/data
    command: server --console-address ":9001" /data

  backend:
    container_name: api
    build: ../backend
    image: playtorr-api
    command: npm run start
    ports:
      - ${MAIN_API_PORT}:${MAIN_API_PORT}

volumes:
  storage-minio:
    external: true